name: deploy to test
on:
  push:
    branches: [ master ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MLAB_HOST }}
        username: ${{ secrets.MLAB_HOST_USERNAME }}
        key: ${{ secrets.CICD2_SECRET }}
        port: ${{ secrets.MLAB_HOST_PORT }}
        script: |
          cd /apps/github-workflows/mhealth-apps/
          sudo rm -rf mLab
          sudo mkdir mLab/
          sudo chown -R cicd2:cicd2 mLab
          git config --global --add safe.directory /apps/github-workflows/mhealth-apps/mLab
          cd mLab
          sudo git clone -b master https://github.com/palladiumkenya/mLab.git .
          git status
          sudo composer install --optimize-autoloader --no-dev
          sudo cp -R /apps/dockerApps/mlabtestsite/nginx /apps/github-workflows/mhealth-apps/mLab
          sudo cp  /apps/dockerApps/mlabtestsite/nginx.dockerfile /apps/github-workflows/mhealth-apps/mLab
          sudo cp  /apps/dockerApps/mlabtestsite/.env /apps/github-workflows/mhealth-apps/mLab
          sudo cp  /apps/dockerApps/mlabtestsite/php.dockerfile /apps/github-workflows/mhealth-apps/mLab
          docker-compose down
          docker-compose up --build -d
          docker-compose exec -T php php artisan key:generate
          docker-compose exec -T php php artisan config:cache
          docker-compose exec -T php php artisan view:cache
          docker-compose exec -T php php artisan route:cache
          docker-compose exec -T php chmod -R 777 storage/
